project:
  type: website
  output-dir: docs

website:
  title: "video-name"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Baseball.Rmd
        text: This is wwhat they clcik on to get to my project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



