project:
  type: website
  output-dir: docs

website:
  title: "Statistical_modeling"
  #subtitle: "Baseball and the shift in salaries"
  #about: "Statistical modeling project using RStudio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Baseball.Rmd
        text: Baseball Project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



